# config.ini

#yt_ is youtube longform
#sh_ is youtube shorts
#lv_ is youtube live
#tw_ is twitch
#tt_ is tiktok
#in_ is instagram
#x_ is X/Twitter

[yt_longform]
scan_age = 45
min_videos = 4
max_videos = 30

fresh_age = 7
fresh_threshold = 0.75
fresh_outlier_multiplier = 3.0 

non_mid_roll_ads = 3.0 #tweak this
mid_roll_threshold = 480
seconds_per_midroll_ad = 600 #tweak this
sponsor_multipliers.integrated = 5.0 #tweak this
sponsor_multipliers.dedicated = 10.0 #tweak this
outlier_range = 0.15

[yt_shorts]
scan_age = 45
min_videos = 4
max_videos = 30
fresh_age = 2
fresh_threshold = 0.75
fresh_outlier_multiplier = 3.0
sponsor_multiplier = 3.3
outlier_range = 0.185

[yt_streams]
scan_age = 45
min_videos = 4
max_videos = 30
fresh_age = 4
fresh_threshold = 0.75
fresh_outlier_multiplier = 3.0
sponsor_multiplier = 2.0
outlier_range = 0.185

[twitch]
static_multiplier = 1.14
outlier_range = 0.15

[tiktok]

[instagram]

[x_twitter]